# -*- coding: utf-8 -*-
"""ModelDeployment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSX_TmGL4BVSjtwLNTKjockjO7meL-Bn
"""

import pandas as pd
import pickle

def predict_new_data(input_data, model_path='new_best_model.pkl'):
    # Load model and preprocessing tools
    with open(model_path, 'rb') as f:
        saved = pickle.load(f)
    model = saved['model']
    scaler = saved['scaler']
    label_encoders = saved['label_encoders']

    # Preprocess input
    df = pd.DataFrame([input_data])
    for col, le in label_encoders.items():
        if col in df.columns:
            df[col] = le.transform(df[col])

    df_scaled = scaler.transform(df)

    # Predict
    return model.predict(df_scaled)[0]